version: "3"
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website
    environment:
      WEBSITE_PORT: 3000
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 80:3000
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodb: {}
